FROM python:3.10.11 as web-image

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_DISABLE_PIP_VERSION_CHECK 1

WORKDIR /code
ADD web-requirements.txt requirements.txt
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN apt-get update \
 && apt-get install -y gcc \
 && pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir setuptools wheel \
 && pip install --no-cache-dir -r requirements.txt \
 && rm -rf /var/lib/apt/lists/*
COPY Makefile Makefile
COPY src/onboarding src
HEALTHCHECK --interval=30s --timeout=5s \
  CMD curl -f http://localhost:5001/ || exit 1
EXPOSE 8000
CMD ["make", "web"]